# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        ElearningBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_users:
           entity: {class: ElearningBundle:User, property: email}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                username_parameter: elearning_login[email]
                password_parameter: elearning_login[password]
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: /logout
                target: elearning_homepage
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/categories, roles: IS_AUTHENTICATED_FULLY }
    access_denied_url: /
