ElearningBundle\Entity\Lesson:
    type: entity
    repositoryClass: ElearningBundle\Repository\LessonRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        correctTotal:
            type: integer
            column: correct_total
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
    manyToOne:
        user:
            targetEntity: User
            inversedBy: lessons
            joinColumn:
                name: user
                referencedColumnName: id
        category:
            targetEntity: Category
            inversedBy: lessons
            joinColumn:
                name: category
                referencedColumnName: id
    oneToMany:
        results:
            targetEntity: Result
            mappedBy: lesson
