ElearningBundle\Entity\Word:
    type: entity
    repositoryClass: ElearningBundle\Repository\WordRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: 255
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
    oneToMany:
         results:
             targetEntity: Result
             mappedBy: word
         answers:
             targetEntity: Answer
             mappedBy: word
             cascade: ["persist"]
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: words
            joinColumn:
                name: category
                referencedColumnName: id
